### ISSUE TITLE
Readme skal opdatéres

### ISSUE THREAD

**Issue by deterherligt** [TK-IT/drinkskort#10]
Der er kommet nye features der ikke er dokumenteret

**Comment by deterherligt** [comment]
Endnu nyere feature er at mixingcard nu fås i to forskellige formater. Et der er som det gamle, og et der er i den rækkefølge man bruger ting.

**Comment by jakobmoss** [comment]
Uhh, fancy! Det skal også tilføjes til make-filen så :)

**Comment by jakobmoss** [comment]
Done!
