### ISSUE TITLE
Python 3 requirements

### ISSUE THREAD

**Issue by neic** [TK-IT/drinkskort#13]
I `Makefile` bliver `python3` kaldt. Hvis man ikke har python 3 fejler det. (eks. python fra OSX)

Det ser ud som om det virker ved at ændre det til `python` (2.7.10).

Bliver der brugt python 3 specifikke ting?

**Comment by jakobmoss** [comment]
Jeg tror mest vi anvender Python 3 af princip. Tingene burde virke med 2.7 også.
Jeg undersøger lige sagen og fikser Makefile'n, så den kan håndtere Python 2 også.
