### ISSUE TITLE
Tutorfest ting

### ISSUE THREAD

**Issue by neic** [TK-IT/drinkskort#14]
Tutorfesten (sikkert som de eneste) vil gerne have skrevet `drinks_bar.pdf` med 8 navne pr. ark, ingen pris (se #12) og ingen ingredienser.

Hvis man gerne vil kode, kan man lave det, men det er ikke noget der kommer til at spare meget tid.

**Comment by Mortal** [comment]
Flyttet til https://github.com/TK-IT/web/issues/253
