### ISSUE TITLE
Find filer i fester/ mappen

### ISSUE THREAD

**Issue by OEHC** [TK-IT/drinkskort#15]
For at persistere de forskellige blandelister, gemmes de fleste input-filer i mappen fester/. For at gøre det let og hurtigt, at genererer lister fra en gammel fest, kunne man altid kigge i fester/ mappen efter den specificerede fil (med fest=NAVN).

**Comment by Mortal** [comment]
Hvordan genererer man lister fra en gammel fest i dag? Hvad vil du gerne have at man kan skrive? Jeg kan kigge på det i aften, men jeg kan ikke huske hvordan man bruger drinkskort.

**Comment by Mortal** [comment]
Lukker gammelt issue - ikke længere relevant når filerne i stedet gemmes i tkweb databasen.
