### ISSUE TITLE
Encodings

### ISSUE THREAD

**Issue by OEHC** [TK-IT/drinkskort#16]
Når ikke computerkyndige SEKR'er retter i inputfilen til SEKR-TeX'en, går fileencoding nogle gange i stykker. Fx. i [fester/Karneval17.txt i e15182e8a7](https://github.com/TK-IT/drinkskort/blob/e15182e8a77fbcf53576b486c418c352a62b6b0d/Karneval17.txt). Kan vi programmere os ud af at detektere det og rette det, før vi compiler med TeX?

**Comment by Mortal** [comment]
Hvad mener du der er i vejen med Karneval17.txt? Den er UTF-8 med UNIX line endings ligesom resten af filerne i 'fester'. `make fest=Karneval17` virker fint.

Hvis det er et problem med at det er Latin-1 i stedet for UTF-8 eller Windows line endings i stedet for UNIX, så kan vi godt kode os ud af det.

**Comment by Mortal** [comment]
Lukker gammelt issue - ikke længere relevant (alt er UTF8 på prodekanus).
