### ISSUE TITLE
Python version on IMF computers

### ISSUE THREAD

**Issue by deterherligt** [TK-IT/drinkskort#3]
Only python 2.3.4 is installed on all imf computers. On orc05 there is a older version of python3 (3.1.3) Neither can run the script.

**Comment by jakobmoss** [comment]
Nu er terminalerne skiftet, men der er vist nogle opstartsvanskeligheder... Og man ssh'er stadig ind på de gamle orker...

**Comment by jakobmoss** [comment]
Det burde virke fint på terminalerne, men man ssh'er stadig ind på det gamle system.... Det burde dog kunne køre på kammerets CS-konto.
Jeg arbejder videre på sagen :)

**Comment by Mortal** [comment]
Lukker gammelt issue - ikke længere et problem nu hvor drinkskort kører på prodekanus.
