### ISSUE TITLE
Ugly makefile

### ISSUE THREAD

**Issue by jakobmoss** [TK-IT/drinkskort#8]
The makefile is ugly... I will fix it! Hence, this is just a reminder to myself :)

**Comment by Mortal** [comment]
I have changed the Makefile now to avoid combinatorial explosion.

**Comment by jakobmoss** [comment]
Jeg synes ikke jeg kan se nogle ændringer..?

**Comment by Mortal** [comment]
I didn't push a651616 yesterday it seems.

**Comment by jakobmoss** [comment]
Nice! I fixed a small error and made a few other chages.
